<style>
	/*    Generated by http://www.cssportal.com    */

/* @import url("reset.css");*/
/*
p, h1 {
    padding: 10px;
}

#wrapper {
    margin: 0 auto;
    width: 1100px;
}

#header {
    float: left;
    height: 80px;
    width: 1100px;
}

#footer {
    height: 50px;
    width: 1100px;
    clear: both;
}
*/
</style>

<script>
	import Navigation from "./nav.svelte"
	//import LeftColumn from "./leftColumn.svelte"
	import Content from "./content.svelte"
	import ResourceSelect from "./resourceSelect.svelte";
</script>

<div class="w-9/12 ">
	<div id="header">
		<h1 class=" text-token text-center font-heading-token h1">Test</h1>
	</div>
	<Navigation />
	<div class="flex w-full">
		<ResourceSelect />
		<Content />
	</div>
	
	<div id="footer">
		<p>This is the Footer</p>
	</div>
</div>